;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Data.Damage.Amount",DevComment="")
+GameplayTagList=(Tag="Gameplay.Action.jump",DevComment="")
+GameplayTagList=(Tag="Gameplay.Action.Jumping",DevComment="")
+GameplayTagList=(Tag="Gameplay.Rule.Death",DevComment="")
+GameplayTagList=(Tag="Gameplay.Rule.Stun",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Action",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Action.Buff",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Action.LockOn",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Action.OnShield",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Action.OnWeapon",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Action.Potion",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Action.WeaponState",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Attack",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Attack.Fire",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.BackStab_CT",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Buff.ATK_UP",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Impact.Damage",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Move",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Move.Look",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Move.Roll",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.OnAir",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.OnAir.Jump",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Player.Buff",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Player.Damage",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Poison",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Buff.ATK_UP",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Buff.DEF_UP",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Buff.GodMode",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Buff.Invincibility",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Buff.PowUp",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.State.NotControl",DevComment="")
+GameplayTagList=(Tag="GamePlayEffect.State.OnScene",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.State.ShieldImpact",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.State.SP_Recovery",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.State.Stun",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.State.WeaponOff",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.State.WeaponOn",DevComment="")
+GameplayTagList=(Tag="InputTag.Attack",DevComment="")
+GameplayTagList=(Tag="InputTag.BackStab",DevComment="")
+GameplayTagList=(Tag="InputTag.Fire",DevComment="")
+GameplayTagList=(Tag="InputTag.Interaction",DevComment="")
+GameplayTagList=(Tag="InputTag.Jump",DevComment="")
+GameplayTagList=(Tag="InputTag.LockOn",DevComment="")
+GameplayTagList=(Tag="InputTag.Look",DevComment="")
+GameplayTagList=(Tag="InputTag.Move",DevComment="")
+GameplayTagList=(Tag="InputTag.Potion",DevComment="")
+GameplayTagList=(Tag="InputTag.Roll",DevComment="")
+GameplayTagList=(Tag="InputTag.Skill_R",DevComment="")
+GameplayTagList=(Tag="InputTag.Weapon",DevComment="")

